### ISSUE TITLE
pyside6

### ISSUE THREAD

**Issue by jamesdbrock** [nix-community/poetry2nix#1191]
Can I use __poetry2nix__ with __pyside6__?

It looks like __pyqt5__ has special overrides.

https://github.com/nix-community/poetry2nix/blob/4f91d45e39cf64b642c6d2725c7bd50d6fcb544b/overrides/default.nix#L2133-L2149

Would I have to write a simliar override?

Here is __pyside6__ in __nixpkgs__:

https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/python-modules/pyside6/default.nix

**Comment by jamesdbrock** [comment]
This works, though I’m not sure if this is a good idea.

```nix
    let
      pkgs = import inputs.nixpkgs {
        inherit system;
        overlays = [ inputs.poetry2nix.overlay ];
      };
    in
        poetryEnv = (pkgs.poetry2nix.mkPoetryEnv {
          overrides = pkgs.poetry2nix.overrides.withDefaults
            (pyfinal: pyprev: {
              pyside6 = pyfinal.pkgs.python3.pkgs.pyside6;
              shiboken6 = pyfinal.pkgs.python3.pkgs.shiboken6;
              pyqt6 = pyfinal.pkgs.python3.pkgs.pyqt6;
              pyqt6-sip = pyfinal.pkgs.python3.pkgs.pyqt6-sip;
            });
        }).env;
```

**Comment by l0b0** [comment]
poetry2nix overrides are generally updated by community members who detect an issue, write their own override, check that it works, and then submit the override for inclusion in poetry2nix. This is normal and expected, since there's no way the poetry2nix maintainers can stay on top of all of the build setup changes necessary for the full Python ecosystem.

It would be great if you could submit a pull request to add your override to `overrides/default.nix`. There are plenty of examples in that file, plus tests in the `tests` directory.
