### ISSUE TITLE
Old version of poetry

### ISSUE THREAD

**Issue by brianmay** [nix-community/poetry2nix#1217]
The commit says we should have version 1.3.2:

https://github.com/nix-community/poetry2nix/commit/ce5d417de0a07a9007a359b7b3f7b6c984ab204b

But it looks like we only have 1.3.0:

$ poetry -V
Poetry (version 1.3.0)

$ which poetry
/nix/store/z6s4c81inn8s91fik8iahxlfccnz5agj-python3.10-poetry-1.3.2/bin/poetry

In actual fact version 1.5.1 is now available: https://github.com/python-poetry/poetry/blob/master/CHANGELOG.md

**Comment by Dessix** [comment]
https://github.com/TheseusInstitute/poetry2nix updates to 1.5.1 but recent changes upstream have broken builds due to some mysterious dependency on lockfile. I'm not entirely sure how to fix this, but I'd definitely appreciate a newer version of poetry- or, at the very least, synchronization with the now much-newer version provided in nixpkgs.
If anyone can manage to rebase the above branch to current upstream, I'd gladly make a PR to update the poetry version in poetry2nix itself.

**Comment by Dessix** [comment]
I've created #1255 in an attempt to fix this, though my linked repository is now using 1.6.0's development branch, if you want to be on the bleeding edge.
