### ISSUE TITLE
Unknown orjson version: '3.9.5'. Please update getCargoHash.

### ISSUE THREAD

**Issue by rigond** [nix-community/poetry2nix#1280]
Where do you find the sha256 to add to the overrides?

**Comment by Pegasust** [comment]
My previous comment is not applicable since `orjson` is now relying on `ahash` with `3.9.x`. Let's take `3.7.1` for example, goes the positive path and shows something similar to https://github.com/nix-community/poetry2nix/pull/1116

For now, please pin orjson to a supported latest version (3.8.11 as of time of writing)

```toml
[tool.poettry.dependencies]
# ...
orjson = "3.8.11"
# ...
```

Or add `preferWheels` (I have to do it regardless with `tiktoken`, never had the time to compile it correctly on darwin)

```nix
my-package = pkgs.poetry2nix.mkPoetryApplication {
  projectDir = ./path/to/my-package;
  # NB: use wheels, easy mode.
  preferWheels = true;
};
```
