### ISSUE TITLE
can't run my program executable (console_script) via mkPoetryApplication

### ISSUE THREAD

**Issue by teto** [nix-community/poetry2nix#159]
I am trying to convert my project to poetry, it's a cli interactive application. I was annoyed by https://github.com/python-poetry/poetry/issues/1279 but could fix it by committing the generated poetry setup.py file.

Now once I am in a nix-shell (`poetry2nix.mkPoetryApplication {`), I can't run my software (executable is called `mptcpanalyzer`) because of:
```
Traceback (most recent call last):
  File "/run/user/1000/tmp.fnf8TG4JP9/bin/mptcpanalyzer", line 33, in <module>
    sys.exit(load_entry_point('mptcpanalyzer', 'console_scripts', 'mptcpanalyzer')())
  File "/run/user/1000/tmp.fnf8TG4JP9/bin/mptcpanalyzer", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/nix/store/fjgnz0xfl04hsblsi4ym5y5akfh6mlmy-python3-3.8.5/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/nix/store/fjgnz0xfl04hsblsi4ym5y5akfh6mlmy-python3-3.8.5/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: mptcpanalyzer
```
Not sure what's the error here, wether it's nix or poetry's *fault*.

If you wanna try/check, just run `nix-shell` on this code https://github.com/teto/mptcpanalyzer/pull/35
I am using nixpkgs c59ea8b8a0e7f927e7291c14ea6cd1bd3a16ff38

**Comment by takeda** [comment]
You are using nix-shell to execute it, but `mkPoetryApplication` is meant for building a final executable. E.g. you can place it in `default.nix` and build using `nix-build`.

There's `mkPoetryEnv` which from my understanding is meant for `nix-shell`. It is the equivalent of installing package in dev mode(`pip -e .`). Until recently it didn't support creating binaries from `tool.poetry.scripts` but that was just added. You might still run into [this](https://github.com/nix-community/poetry2nix/issues/163) issue if you make use of `pkg_resources` (although since it is your application you probably can replace it with `importlib.metadata`.

If you want to use nix to package application for regular use and not development, you should invoke `mkPoetryApplication` via nix build, and as far as I can tell that works correctly without any issues.

**Comment by teto** [comment]
thanks for the help, but mkPoetryEnv doesnt even generate the `mptcpanalyzer` script so not sure it's the correct way (even when setting editablePackageSources).

**Comment by takeda** [comment]
How old is your poetry2nix? Because, this functionality was added very recently: https://github.com/nix-community/poetry2nix/pull/150

**Comment by teto** [comment]
I am using the one from nixpkgs so maybe that's why: I doubt it has this change. With nix flakes, is there a way to override nixpkgs' poetry with this repo's ?

**Comment by takeda** [comment]
You can use overlays and poetry2nix makes it esier since it creates `overlay.nix` that you can just include and will overwrite version of poetry2nix and poetry itself.

I personally use niv to pin packages to specific version, I guess I won't need it once flakes are officially released.

But basically to set it up I do:

```shell
$ niv init
$ niv modify nixpkgs -b nixpkgs-unstable
$ niv add nix-community/poetry2nix
```

Then place a `nix/default.nix` file:

```nix
{ ... }@args:
let
  sources = import ./sources.nix;

  # remove overlays and config attributes from args
  clean_args = builtins.removeAttrs args [ "overlays" "config" ];
in import sources.nixpkgs {
  overlays = [
    # latest version of poetry and poetry2nix
    (import "${sources.poetry2nix}/overlay.nix")
    (self: super: {
      inherit sources;
      inherit (import sources.niv { pkgs = super; }) niv;
    })
  ];
  config = {};
} // args
```

Now instead of `import <nixpkgs> {}` you do `import ./nix {}`. This will provide nixpkgs as usual, except it will be pinned. You can later use `niv update` to get latest versions.

Of course if you don't want to use niv, you can just provide the overlay, you can use `builtins.fetchGit` or `fetchFromGitHub` and then reference 1overlay.nix` similar as it is done in `default.nix`.

**Comment by teto** [comment]
arf I tried your suggestion and added poetry2nix as an overlay to nixpkgs to get the latest version, Yet I get the same issue as in my first post https://github.com/nix-community/poetry2nix/issues/159#issue-686606356 :(

**Comment by teto** [comment]
Maybe I misunderstood you. Do you mean I should add importlib-metadata as a dependency of my program for it to work ?
within my poetry nix-shell
```
>>> from importlib.metadata import *
>>> entry_points()
```
I can't find my package "mptcpanalyzer", which kinda similar to the first error, aka the current package being developed is not added to the list of importlib-metadata.

**Comment by teto** [comment]
I added importlib-metadata and that fixed it \o/ I don't if it's the final fix, but it should at least be documented. Thanks for the help.

**Comment by teto** [comment]
my bad I was still running my old version that relies on nixpkgs+setup.py

**Comment by teto** [comment]
I followed the advice in https://github.com/NixOS/nixpkgs/issues/105593 and just tweaking PYTHONPATH works fine.
