### ISSUE TITLE
Flake with multiple dev shells, mkPoetryEnv is one of them

### ISSUE THREAD

**Issue by KaliszS** [nix-community/poetry2nix#1632]
I started my adventure with Nix recently, but I'll admit that I'm already running out of patience with poetry2nix. I have tried many solutions from this repository and from other corners of the internet, but I keep running into the same errors over and over again. I would be very grateful for your help.

I need different devShells, because mkPoetryEnv itself does not have shellHooks.

```nix
{
  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    poetry2nix = {
      url = "github:nix-community/poetry2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, flake-utils, nixpkgs, poetry2nix }:
    (flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in with pkgs; rec {
        devShells = rec {
          # pythonEnv = mkShell {
          #   buildInputs = [
          #     python3
          #     poetry
          #   ];
          # };
          pythonEnv = poetry2nix.mkPoetryEnv {
            projectDir = ./.;
            python = python3;
          };

          geoEnv = mkShell {
            buildInputs = [
              gdal
              geos
            ];
            shellHook = ''
              echo "Exporting environmental variables..."; set -o allexport; source .env; set +o allexport
              echo "Installing and updating python packages..."; poetry update
            '';
          };

          default = mkShell { inputsFrom = [ pythonEnv geoEnv ]; };
        };
      }
    ));
}

```

Code above returns `attribute 'mkPoetryEnv' missing`. With solutions from README I've got another error, that overlay should be replaced by overlays, but then it doesn't work anyway.

What should I change in orderd to use `nix develop` succesfully? Commented `pythonEnv` shell works correctly.

**Comment by onethirtyfive** [comment]
Welcome to Nix. It's quite *simple* in the end, but not at all *easy*.

Here's why you're getting the error you're getting. Flake inputs are just downloads of something:
  
```nix
  poetry2nix.url = "github:nix-community/poetry2nix";
```

Inputs have a property which is important, but hidden, until you know about it:

```nix
  poetry2nix.flake = true; # defaults to true
````

In your flake, since nix downloads the input with `flake = true`, it will evaluate that downloaded source's `flake.nix` for you. This evaluated attrset is what gets passed to `outputs`. So you can understand the error you see by reasoning about [those outputs](https://github.com/nix-community/poetry2nix/blob/d11c01e58587e5f21037ed6477465a7f26a32e27/flake.nix#L30-L144).

There is--literally, to the letter--no poetry2nix flake output named `mkPoetry2Nix`. This is the error you're getting: you can't ask an attrset for an attr it doesn't have. The error isn't magic, it's pedantry.

But there _is_ a [lib.mkPoetry2Nix](https://github.com/nix-community/poetry2nix/blob/master/flake.nix#L32). And this is what poetry2nix gives you to bootstrap: a function which you must provide with a specific `pkgs`, which gives you back an attrset containing the APIs you're looking for, configured for your use case.

You were super close in your example code. Try this:

```nix
{
  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
    poetry2nix.url = {
      url = "github:nix-community/poetry2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, flake-utils, nixpkgs, poetry2nix }:
    (flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        inherit (pkgs) mkShell;

        mkPoetryEnv =
          let
            # Here's one way:
            poetry2nix' = poetry2nix.lib.mkPoetry2Nix { inherit pkgs; };
            inherit (poetry2nix') mkPoetryEnv; # or any other offering of poetry2Nix, like mkPoetryPackages

            # Here's another way. Same thing, but one-liner. You pick:
            # inherit (poetry2nix.lib.mkPoetry2Nix { inherit pkgs; }) ...;
          in mkPoetryEnv;
      in {
        devShells = rec {
          pythonEnv = mkPoetryEnv {
            projectDir = ./.;
            python = pkgs.python3;
          };

          geoEnv = mkShell {
            buildInputs = with pkgs; [ gdal geos poetry ];
            shellHook = ''
              echo "Exporting environmental variables..."; set -o allexport; source .env; set +o allexport
              echo "Installing and updating python packages..."; poetry update
            '';
          };

          default = mkShell { inputsFrom = [ pythonEnv geoEnv ]; };
        };
      }
    ));
}
```

You probably didn't get an answer because your frustration, while understandable, was you blaming the library for your lack of knowledge.

FOSS is usually unpaid labor. You're only gonna get what you give, and recriminations based on your newbiness are... achingly, boringly common. No one cares if you're almost over Nix--but they might care about helping you.

Here's [an example](https://github.com/nix-community/poetry2nix#quickstart-flakenix) from the README which could have also answered your question.

Stay curious, you've got this. :heart:

**Comment by KaliszS** [comment]
@onethirtyfive I had already forgotten about this issue, but in the meantime I have already solved the problem. No less sincere thanks for your comprehensive reply and for pointing out the tone of my statement.

It was a big mistake on my part not to read the whole thing before publishing, because I admit that from the sidelines it looks very pretentious. I assure you, however, that this was not my intention. I don't know myself what didn't work out, perhaps it's my skill issue not only with Nix but also with the English language, which resulted in an inappropriate choice of words. Perhaps through frustration I focused on the piece of code itself and forgot that there were people behind it whom I might have offended in this way. Anyway, I apologise and assure you that I did not mean to blame anyone for anything.
