### ISSUE TITLE
how to write a devShell to mimic `nix develop` on defaultPackage

### ISSUE THREAD

**Issue by teto** [nix-community/poetry2nix#325]
Let's say I have a flake similar to 
```
      packages.novops = let
        in poet.mkPoetryApplication {
          projectDir = ./.;
        };

      defaultPackage = packages.novops;
      defaultApp = flake-utils.lib.mkApp { name = "novops"; drv = packages.novops;};

      # if i comment this, nix develop works fine
      devShell = pkgs.mkShell {
        name = "shell";
        buildInputs = [
          poetry.packages."${system}".poetry
          defaultPackage.inputDerivation
          pkgs.nodePackages.pyright
        ];

        # shellHook = defaultPackage.shellHook;
      };
```
If I comment out the devShell part and run `nix develop`, then I can do `export PYTHONPATH="$PWD:$PYTHONPATH"` and run my python application. 
If I try to customize devShell to customize stuff a bit (cleaner than changing attributes of the python application) then I lose this ability, I think some python hooks are not triggered. How can I fix that ?

**Comment by FRidh** [comment]
What's needed is a `shellHook`. So far, only the `setuptools` backend has a `shellHook`, because it's the only backend that supports development mode. PEP 660 has been accepted, and in the future, `buildPythonPackage` will use `pyproject` as default backend, which will then support PEP 660. This is really for in Nixpkgs to fix.

**Comment by teto** [comment]
thanks
