### ISSUE TITLE
How to include a poetry2nix flake in another flake

### ISSUE THREAD

**Issue by charmoniumQ** [nix-community/poetry2nix#391]
Minimal (not) working example:
```
git clone https://github.com/charmoniumQ/poetry2nix-flake-test
cd test1
nix shell
python -c 'import test1'
# The flake for test1 works.
cd test2
nix develop
# The flake for test2 should import test1
python -c 'import test1'
# ModuleNotFoundError
```

**Comment by bbenne10** [comment]
I think there're two basic issues here. 

Firstly, I think you're not getting the `test1` you think you are in the first `python -c 'import test1` invocation.
I'd venture to guess that if you did `python -c 'import test1; print(test1.__file__)` it would point to the repository rather than the nix store.
This is a common issue with testing python code as well, which is why we have adopted a `src` directory oriented approach to packaging as it prevents you from importing modules accidentally.

Secondly, `mkPoetryApplication` does not expose the result as a python module. I believe you should be using `mkPoetryEnv` for this.

**Comment by adisbladis** [comment]
Flakes are experimental, and issues with those are not something I'd like to deal with as a downstream.
