### ISSUE TITLE
`testpath` wants `flit` (probably?)

### ISSUE THREAD

**Issue by kirelagin** [nix-community/poetry2nix#547]
### Describe the issue

I am trying to build something (jupyter) and I am getting:

```text
ModuleNotFoundError: No module named 'flit'
```

when it is building `testpath`.

I have no idea what I am doing, but I changed `flit-core` to `flit` in `build-systems.json` and it seems to work now.

I would probably submit a PR with this change, but, as I said, I have absolutely no idea about anything in here (and there doesn’t seem to be any documentation for this build-systems magic).

**Comment by adisbladis** [comment]
> I have no idea what I am doing, but I changed flit-core to flit in build-systems.json and it seems to work now.

That sounds correct. This list of build systems was created on a best effort basis and upstream changed from `flit` to `flit-core` with the release of 0.5.0: https://github.com/jupyter/testpath/commit/0a8115a8aee8576ce7ef9b70d29c30c8f8b95e2f.

Using `flit` rather than `flit-core` should be safe even for newer versions so that change sounds good to me.
