### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by domenkozar** [nix-community/poetry2nix#84]
`error: attribute 'pyramid_retry' missing, at /nix/store/bj56vllyvxfn7y2chm6l53rimyh9jmms-source/pkgs/development/tools/poetry2nix/poetry2nix/mk-poetry-dep.nix:132:28`

I'm not entirely sure what's going on, pyramid_retry only appears in `poetry.lock`. It seems like something depends on it before `pythonPackages.pyramid_retry` is created?

I can put together an example repo if that would help.

cc @adisbladis

**Comment by domenkozar** [comment]
By overriding a few packages to be `null` I get to:

```
$ nix-build 
error: stack overflow (possible infinite recursion)
```

How did you debug this?

**Comment by Infinisil** [comment]
After looking into this, I figured out the following.

For one it seems that [poetry replaces all `-` with `_` internally](https://github.com/python-poetry/poetry/blob/32e457b78e79a93563f9c4b7802cd90d8344fe4b/poetry/utils/helpers.py#L29-L30), meaning it doesn't distinguish between `pyramid-retry` and `pyramid_retry`. And according to pypi, it's `pyramid-retry`, but the [project](https://github.com/niteoweb/pyramid_deferred_sqla) we have as a dependency [specifies this as `pyramid_retry`](https://github.com/niteoweb/pyramid_deferred_sqla/blob/639b822d16aff7d732a4da2d3752cfdecee00aef/setup.py#L49), which leads to the following abbreviated lock file:

```toml
# ...

[[package]]
name = "pyramid-deferred-sqla"

[package.dependencies]
pyramid_retry = "*"

# ...

[[package]]
name = "pyramid-retry"

# ...

pyramid-retry = [
    {file = "pyramid_retry-2.1.1-py2.py3-none-any.whl", hash = "sha256:b5129a60eb9d7409234ea52839006426d2ae887b4a1f0530c75ec336cabf2476"},
    {file = "pyramid_retry-2.1.1.tar.gz", hash = "sha256:baa8276ae68babad09e5f2f94efc4f7421f3b8fb526151df522052f8cd3ec0c9"},
]
```

Note how both `pyramid_retry` and `pyramid-retry` are occuring. I believe this is something that should be fixed in poetry2nix by transforming all package names in the same way internally.

--- 

Furthermore, for the stack overflow error, this seems to be partially caused by our use of `gitignoreSource` from https://github.com/hercules-ci/gitignore.nix.  Namely this causes the error:

```nix
poetry2nix.mkPoetryApplication {
  projectDir = gitignoreSource ./.;
}
```

While this works:

```nix
poetry2nix.mkPoetryApplication {
  projectDir = ./.;
}
```

and so does this:

```nix
poetry2nix.mkPoetryApplication {
  src = gitignoreSource ./.;
  pyproject = ./pyproject.toml;
  poetrylock = ./poetry.lock;
}
```

I feel like this is a problem with poetry2nix's handling of `projectDir`.

**Comment by gilligan** [comment]
I’m on the road so just a quick remark: i definitely think that poetry should take care of sanitizing identifiers and not poetry2nix. I’ve been meaning to file an issue for a while will do so today..

**Comment by adisbladis** [comment]
I created an issue for this back in February: https://github.com/python-poetry/poetry/issues/2098.

**Comment by adisbladis** [comment]
> I feel like this is a problem with poetry2nix's handling of projectDir.

`projectDir` was never intended as a full replacement for the `src` attribute, it's a shortcut to provide arguments relative to a project root like `pyproject.toml`, `poetry.lock` & friends.
If you want to apply custom source filtering use the `src` attribute, it's fine to use that together with `projectDir`.

**Comment by adisbladis** [comment]
> i definitely think that poetry should take care of sanitizing identifiers

Absolutely this logic belongs in Poetry. There is no canonical way to canonicalise (heh) names with regards to casing & potentially other identifiers. 
The case of `_` vs `-` looks easy but it opens the floodgates to tons of tiny hacks that will never work 100%.

For now my only recommendation is to ensure your `pyproject.toml` is using canonical names.

**Comment by Infinisil** [comment]
@adisbladis This wouldn't help in this case, since the names with `_` come from pyramid-deferred-sqla's setup.py. A PR to change those to `-` would probably fix it though.

**Comment by YPares** [comment]
I think this issue is back with latest nixpkgs-unstable.

When building a package depending on uvicorn, it fails with:

```
error: attribute 'optional-dependencies' missing
       at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/pkgs/development/python-modules/fastapi-cli/default.nix:31:8:
           30|     uvicorn
           31|   ] ++ uvicorn.optional-dependencies.standard;
             |        ^
           32|
```

**Comment by elikoga** [comment]
> I think this issue is back with latest nixpkgs-unstable.
> 
> When building a package depending on uvicorn, it fails with:
> 
> ```
> error: attribute 'optional-dependencies' missing
>        at /nix/store/sh0v21n9zc03b94qjj4jkkg5mbsjkpzr-source/pkgs/development/python-modules/fastapi-cli/default.nix:31:8:
>            30|     uvicorn
>            31|   ] ++ uvicorn.optional-dependencies.standard;
>              |        ^
>            32|
> ```

Just saw it, doesn't look like the same error to me

**Comment by elikoga** [comment]
https://github.com/NixOS/nixpkgs/commit/543781083afffe71d6250862eb494c244355fa11

This is obviously the culprit

**Comment by squat** [comment]
@YPares @elikoga I'm pretty sure the issue you are describing is unrelated. It looks like https://github.com/NixOS/nixpkgs/pull/365075 to me, which is a packaging bug in fastapi-cli
